server {
    listen 80;
    server_name _;
    root /app/scoring/public;
    index index.php index.html;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /app/scoring/public$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /app/scoring/public;
    }

    location ~ /\.ht {
        deny all;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}